defaults:
  - analyze_latent

batch_size: 10

reducer:
  _target_: umap.UMAP

feature_names:
  - Day
  - cellType
  - Cytoplasm_Texture_Variance_Mito_20_01
  - Cytoplasm_Granularity_9_AGP
  - prs.5cluster3_obesity
  - gps_homairadjbmi
  - gps_t2d
  - gps_fastinsulin
  #- Cells_Granularity_1_AGP
  - ENSG00000189339
  - ENSG00000134202
  - ENSG00000134184
  - ENSG00000240342

model:
  num_hidden:
    - 1000
  num_latent: 50
  beta: .001

training_loop:
  lr: 1e-4
  num_epochs: 300
  kld_warmup_steps:
    - 50
    - 100
    - 125
    - 150
    - 175
    - 200
    - 225
    - 250
    - 275
    #- 300
    # - 325
    # - 350
    # - 375