defaults:
  - identify_associations_ks_schema

batch_size: 10

num_refits: 32
sig_threshold: 0.01

target_dataset: Cyto
target_value: plus_std
save_refits: True

model:
  categorical_weights: ${weights:${data.categorical_inputs}}
  continuous_weights: ${weights:${data.continuous_inputs}}
  num_hidden:
    - 500
  num_latent: 200
  beta: .0001
  dropout: 0.1
  cuda: false

training_loop:
  lr: 1e-4
  num_epochs: 300
  kld_warmup_steps:
    - 50
    - 100
    - 125
    - 150
    - 175
    - 200
    - 225
    - 250
    - 275
  early_stopping: false
  patience: 0

perturbed_feature_names:
  - prs.5cluster3_obesity
target_feature_names:
  - gps_t2d