
defaults:
  - identify_associations_bayes

batch_size: 10

num_refits: 32
sig_threshold: 0.05

target_dataset: Cyto
target_value: plus_std
save_refits: True

model:
  num_hidden:
    - 500
  num_latent: 200
  beta: .0001

training_loop:
  lr: 1e-4
  num_epochs: 300
  kld_warmup_steps:
    - 50
    - 100
    - 125
    - 150
    - 175
    - 200
    - 225
    - 250
    - 275