
defaults:
  - identify_associations_ks

batch_size: 16

num_refits: 10 
sig_threshold: 0.05

target_dataset: aligned_mgx
target_value: plus_std
save_refits: True

model:
  categorical_weights: ${weights:${data.categorical_inputs}}
  continuous_weights: ${weights:${data.continuous_inputs}}
  num_hidden:
    - 256
  num_latent: 32
  beta: .0001
  dropout: 0.1
  cuda: false

training_loop:
  lr: 1e-4
  num_epochs: 400
  batch_dilation_steps:
    - 50
    - 100
    - 150
  kld_warmup_steps:
    - 50
    - 100
    - 150
  early_stopping: false
  patience: 0