defaults:
  - analyze_latent

batch_size: 10

feature_names:
  - RNF144B
  - TWIST2

model:
  num_hidden:
    - 200
  num_latent: 50
  beta: .0001

training_loop:
  lr: 1e-4
  num_epochs: 300
  batch_dilation_steps:
    - 50
    - 100
    - 150
  kld_warmup_steps:
    - 50
    - 100
    - 150
  early_stopping: false
  patience: 0