defaults:
  - analyze_latent

batch_size: 10

feature_names:
  - Continuous_A_1
  - Continuous_A_2
  - Continuous_A_3
  - Continuous_A_4
  - Continuous_A_5
  - Continuous_A_6
  - Continuous_A_7
  - Continuous_A_8
  - Continuous_A_9
  - Continuous_A_10
  - Continuous_B_1
  - Continuous_B_2
  - Continuous_B_3
  - Continuous_B_4
  - Continuous_B_5
  - Continuous_B_6
  - Continuous_B_7
  - Continuous_B_8
  - Continuous_B_9
  - Continuous_B_10
  - Categorical_A_1
  - Categorical_B_1

model:
  num_hidden:
    - 15
  num_latent: 3
  beta: .0001

training_loop:
  lr: 1e-4
  num_epochs: 300
  batch_dilation_steps:
    - 100
    - 200
  kld_warmup_steps:
    - 50
    - 100
    - 125
    - 150
    - 175
    - 200
    - 225
    - 250
    - 275
  early_stopping: false
  patience: 0