
defaults:
  - identify_associations_ttest

batch_size: 10

num_refits: 5 
num_latent:
  - 5
  - 10
  - 15
  - 20

sig_threshold: 0.05

target_dataset: random.random_all_sim.Continuous_B
target_value: plus_std
save_refits: True

model:
  categorical_weights: ${weights:${data.categorical_inputs}}
  continuous_weights: ${weights:${data.continuous_inputs}}
  num_hidden:
    - 50
  num_latent: 10
  beta: .0001
  dropout: 0.1
  cuda: false

training_loop:
  lr: 1e-4
  num_epochs: 200
  batch_dilation_steps:
    - 50
    - 100
    - 150
  kld_warmup_steps:
    - 50
    - 100
    - 150
  early_stopping: false
  patience: 0
