defaults:
  - analyze_latent

batch_size: 10

feature_names:
  - Continuous_A_1
  - Categorical_A_1

model:
  num_hidden:
    - 20
  num_latent: 5
  beta: .001

training_loop:
  lr: 1e-4
  num_epochs: 200
  batch_dilation_steps:
    - 50
    - 100
    - 150
  kld_warmup_steps:
    - 50
    - 100
    - 150
  early_stopping: false
  patience: 0